package com.lanouit.exam.mapper;

import com.lanouit.exam.po.PositionSubject;
import com.lanouit.exam.po.PositionSubjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PositionSubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_subject
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    int countByExample(PositionSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_subject
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    int deleteByExample(PositionSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_subject
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_subject
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    int insert(PositionSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_subject
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    int insertSelective(PositionSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_subject
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    List<PositionSubject> selectByExample(PositionSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_subject
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    PositionSubject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_subject
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    int updateByExampleSelective(@Param("record") PositionSubject record, @Param("example") PositionSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_subject
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    int updateByExample(@Param("record") PositionSubject record, @Param("example") PositionSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_subject
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    int updateByPrimaryKeySelective(PositionSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table position_subject
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    int updateByPrimaryKey(PositionSubject record);
}