package com.lanouit.exam.mapper;

import com.lanouit.exam.po.QuestionSubject;
import com.lanouit.exam.po.QuestionSubjectExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.MapperScan;

@MapperScan
public interface QuestionSubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_subject
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    int countByExample(QuestionSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_subject
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    int deleteByExample(QuestionSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_subject
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_subject
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    int insert(QuestionSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_subject
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    int insertSelective(QuestionSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_subject
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    List<QuestionSubject> selectByExample(QuestionSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_subject
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    QuestionSubject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_subject
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    int updateByExampleSelective(@Param("record") QuestionSubject record, @Param("example") QuestionSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_subject
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    int updateByExample(@Param("record") QuestionSubject record, @Param("example") QuestionSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_subject
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    int updateByPrimaryKeySelective(QuestionSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_subject
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    int updateByPrimaryKey(QuestionSubject record);
}