package com.lanouit.exam.po;

import java.util.Date;

public class Exam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.id
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.user_id
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.start_time
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.is_review
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    private Integer isReview;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.position
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.end_time
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.is_submit
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    private Integer isSubmit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.id
     *
     * @return the value of exam.id
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.id
     *
     * @param id the value for exam.id
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.user_id
     *
     * @return the value of exam.user_id
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.user_id
     *
     * @param userId the value for exam.user_id
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.start_time
     *
     * @return the value of exam.start_time
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.start_time
     *
     * @param startTime the value for exam.start_time
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.is_review
     *
     * @return the value of exam.is_review
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    public Integer getIsReview() {
        return isReview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.is_review
     *
     * @param isReview the value for exam.is_review
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    public void setIsReview(Integer isReview) {
        this.isReview = isReview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.position
     *
     * @return the value of exam.position
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.position
     *
     * @param position the value for exam.position
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.end_time
     *
     * @return the value of exam.end_time
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.end_time
     *
     * @param endTime the value for exam.end_time
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.is_submit
     *
     * @return the value of exam.is_submit
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    public Integer getIsSubmit() {
        return isSubmit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.is_submit
     *
     * @param isSubmit the value for exam.is_submit
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    public void setIsSubmit(Integer isSubmit) {
        this.isSubmit = isSubmit;
    }
}