package com.lanouit.exam.po;

import java.util.Date;
import java.util.List;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Null;

import com.lanouit.exam.validator.group.ExamReviewGroup;
import com.lanouit.exam.validator.group.ExamSaveGroup;
import com.lanouit.exam.validator.group.ExamSubmitGroup;
import com.lanouit.exam.validator.group.ExamUpdateGroup;

public class Exam {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column exam.id
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column exam.user_id
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	@Null(groups = { ExamUpdateGroup.class, ExamSubmitGroup.class, ExamReviewGroup.class })
	private Integer userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column exam.start_time
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	@Null(groups = { ExamUpdateGroup.class, ExamSubmitGroup.class, ExamReviewGroup.class })
	private Date startTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column exam.is_review
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	@Null(groups = { ExamSaveGroup.class, ExamReviewGroup.class })
	private Integer isReview;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column exam.position
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	@NotNull(message = "职业名称不能为空", groups = { ExamSaveGroup.class })
	@Null(groups = { ExamSubmitGroup.class, ExamReviewGroup.class })
	private Integer position;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column exam.end_time
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	@Null(groups = { ExamUpdateGroup.class, ExamSubmitGroup.class, ExamReviewGroup.class })
	private Date endTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column exam.is_submit
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	@Null(groups = { ExamSaveGroup.class, ExamSubmitGroup.class, ExamReviewGroup.class })
	private Integer isSubmit;

	/**
	 * 考试详细
	 */
	private List<ExamDetailWithBLOBs> examDetails;

	/**
	 * 考试时间，分钟
	 */
	@NotNull(message = "考试时间不能为空", groups = { ExamSaveGroup.class })
	private Integer examMinute;

	public List<ExamDetailWithBLOBs> getExamDetails() {
		return examDetails;
	}

	public void setExamDetails(List<ExamDetailWithBLOBs> examDetails) {
		this.examDetails = examDetails;
	}

	public Integer getExamMinute() {
		return examMinute;
	}

	public void setExamMinute(Integer examMinute) {
		this.examMinute = examMinute;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column exam.id
	 *
	 * @return the value of exam.id
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column exam.id
	 *
	 * @param id
	 *            the value for exam.id
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column exam.user_id
	 *
	 * @return the value of exam.user_id
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column exam.user_id
	 *
	 * @param userId
	 *            the value for exam.user_id
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column exam.start_time
	 *
	 * @return the value of exam.start_time
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column exam.start_time
	 *
	 * @param startTime
	 *            the value for exam.start_time
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column exam.is_review
	 *
	 * @return the value of exam.is_review
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	public Integer getIsReview() {
		return isReview;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column exam.is_review
	 *
	 * @param isReview
	 *            the value for exam.is_review
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	public void setIsReview(Integer isReview) {
		this.isReview = isReview;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column exam.position
	 *
	 * @return the value of exam.position
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	public Integer getPosition() {
		return position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column exam.position
	 *
	 * @param position
	 *            the value for exam.position
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	public void setPosition(Integer position) {
		this.position = position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column exam.end_time
	 *
	 * @return the value of exam.end_time
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column exam.end_time
	 *
	 * @param endTime
	 *            the value for exam.end_time
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column exam.is_submit
	 *
	 * @return the value of exam.is_submit
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	public Integer getIsSubmit() {
		return isSubmit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column exam.is_submit
	 *
	 * @param isSubmit
	 *            the value for exam.is_submit
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	public void setIsSubmit(Integer isSubmit) {
		this.isSubmit = isSubmit;
	}
}