package com.lanouit.exam.po;

public class ExamDetailWithBLOBs extends ExamDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_detail.answer
     *
     * @mbggenerated Fri Jun 16 20:46:23 CST 2017
     */
    private String answer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_detail.review_analysis
     *
     * @mbggenerated Fri Jun 16 20:46:23 CST 2017
     */
    private String reviewAnalysis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_detail.code
     *
     * @mbggenerated Fri Jun 16 20:46:23 CST 2017
     */
    private String code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_detail.answer
     *
     * @return the value of exam_detail.answer
     *
     * @mbggenerated Fri Jun 16 20:46:23 CST 2017
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_detail.answer
     *
     * @param answer the value for exam_detail.answer
     *
     * @mbggenerated Fri Jun 16 20:46:23 CST 2017
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_detail.review_analysis
     *
     * @return the value of exam_detail.review_analysis
     *
     * @mbggenerated Fri Jun 16 20:46:23 CST 2017
     */
    public String getReviewAnalysis() {
        return reviewAnalysis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_detail.review_analysis
     *
     * @param reviewAnalysis the value for exam_detail.review_analysis
     *
     * @mbggenerated Fri Jun 16 20:46:23 CST 2017
     */
    public void setReviewAnalysis(String reviewAnalysis) {
        this.reviewAnalysis = reviewAnalysis == null ? null : reviewAnalysis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_detail.code
     *
     * @return the value of exam_detail.code
     *
     * @mbggenerated Fri Jun 16 20:46:23 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_detail.code
     *
     * @param code the value for exam_detail.code
     *
     * @mbggenerated Fri Jun 16 20:46:23 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }
}