package com.lanouit.exam.po;

import javax.validation.constraints.Null;

import com.lanouit.exam.validator.group.ExamDetailUpdateGroup;

public class ExamDetail {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column exam_detail.id
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column exam_detail.exam_id
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	@Null(groups = { ExamDetailUpdateGroup.class })
	private Integer examId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column exam_detail.question_id
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	@Null(groups = { ExamDetailUpdateGroup.class })
	private Integer questionId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column exam_detail.score
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	private Double score;

	/**
	 * 试题
	 */
	private QuestionWithBLOBs question;

	public QuestionWithBLOBs getQuestion() {
		return question;
	}

	public void setQuestion(QuestionWithBLOBs question) {
		this.question = question;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column exam_detail.id
	 *
	 * @return the value of exam_detail.id
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column exam_detail.id
	 *
	 * @param id
	 *            the value for exam_detail.id
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column exam_detail.exam_id
	 *
	 * @return the value of exam_detail.exam_id
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	public Integer getExamId() {
		return examId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column exam_detail.exam_id
	 *
	 * @param examId
	 *            the value for exam_detail.exam_id
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	public void setExamId(Integer examId) {
		this.examId = examId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column exam_detail.question_id
	 *
	 * @return the value of exam_detail.question_id
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	public Integer getQuestionId() {
		return questionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column exam_detail.question_id
	 *
	 * @param questionId
	 *            the value for exam_detail.question_id
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	public void setQuestionId(Integer questionId) {
		this.questionId = questionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column exam_detail.score
	 *
	 * @return the value of exam_detail.score
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	public Double getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column exam_detail.score
	 *
	 * @param score
	 *            the value for exam_detail.score
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	public void setScore(Double score) {
		this.score = score;
	}
}