package com.lanouit.exam.po;

import java.util.List;

import javax.validation.constraints.NotNull;

import com.lanouit.exam.validator.group.PositionSaveGroup;
import com.lanouit.exam.validator.group.PositionUpdateGroup;

public class Position {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column position.id
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column position.position_name
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	@NotNull(message = "职业名称不能为空", groups = { PositionSaveGroup.class,
			PositionUpdateGroup.class })
	private String positionName;

	private List<Subject> subjects;

	public List<Subject> getSubjects() {
		return subjects;
	}

	public void setSubjects(List<Subject> subjects) {
		this.subjects = subjects;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column position.id
	 *
	 * @return the value of position.id
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column position.id
	 *
	 * @param id
	 *            the value for position.id
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column position.position_name
	 *
	 * @return the value of position.position_name
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	public String getPositionName() {
		return positionName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column position.position_name
	 *
	 * @param positionName
	 *            the value for position.position_name
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	public void setPositionName(String positionName) {
		this.positionName = positionName == null ? null : positionName.trim();
	}

	@Override
	public String toString() {
		return "Position [id=" + id + ", positionName=" + positionName
				+ ", subjects=" + subjects + "]";
	}

}