package com.lanouit.exam.po;

public class PositionSubject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position_subject.id
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position_subject.position_id
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    private Integer positionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column position_subject.subject_id
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    private Integer subjectId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position_subject.id
     *
     * @return the value of position_subject.id
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position_subject.id
     *
     * @param id the value for position_subject.id
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position_subject.position_id
     *
     * @return the value of position_subject.position_id
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    public Integer getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position_subject.position_id
     *
     * @param positionId the value for position_subject.position_id
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column position_subject.subject_id
     *
     * @return the value of position_subject.subject_id
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column position_subject.subject_id
     *
     * @param subjectId the value for position_subject.subject_id
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }
}