package com.lanouit.exam.po;

import javax.validation.constraints.NotNull;

import com.lanouit.exam.validator.group.QuestionSaveGroup;
import com.lanouit.exam.validator.group.QuestionUpdateGroup;

public class QuestionWithBLOBs extends Question {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.content
     *
     * @mbggenerated Mon Jun 12 15:14:43 CST 2017
     */
	@NotNull(message="试题题目不能为空",groups={QuestionSaveGroup.class,QuestionUpdateGroup.class})
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.question_option
     *
     * @mbggenerated Mon Jun 12 15:14:43 CST 2017
     */
    private String questionOption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answer
     *
     * @mbggenerated Mon Jun 12 15:14:43 CST 2017
     */
    private String answer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.analysis
     *
     * @mbggenerated Mon Jun 12 15:14:43 CST 2017
     */
    private String analysis;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.content
     *
     * @return the value of question.content
     *
     * @mbggenerated Mon Jun 12 15:14:43 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.content
     *
     * @param content the value for question.content
     *
     * @mbggenerated Mon Jun 12 15:14:43 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.question_option
     *
     * @return the value of question.question_option
     *
     * @mbggenerated Mon Jun 12 15:14:43 CST 2017
     */
    public String getQuestionOption() {
        return questionOption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.question_option
     *
     * @param questionOption the value for question.question_option
     *
     * @mbggenerated Mon Jun 12 15:14:43 CST 2017
     */
    public void setQuestionOption(String questionOption) {
        this.questionOption = questionOption == null ? null : questionOption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answer
     *
     * @return the value of question.answer
     *
     * @mbggenerated Mon Jun 12 15:14:43 CST 2017
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answer
     *
     * @param answer the value for question.answer
     *
     * @mbggenerated Mon Jun 12 15:14:43 CST 2017
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.analysis
     *
     * @return the value of question.analysis
     *
     * @mbggenerated Mon Jun 12 15:14:43 CST 2017
     */
    public String getAnalysis() {
        return analysis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.analysis
     *
     * @param analysis the value for question.analysis
     *
     * @mbggenerated Mon Jun 12 15:14:43 CST 2017
     */
    public void setAnalysis(String analysis) {
        this.analysis = analysis == null ? null : analysis.trim();
    }

	@Override
	public String toString() {
		return super.toString() + "----" + "QuestionWithBLOBs [content=" + content + ", questionOption="
				+ questionOption + ", answer=" + answer + ", analysis="
				+ analysis + "]";
	}
    
}