package com.lanouit.exam.po;

import java.util.Date;

public class Question {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.id
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.type
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.score
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    private Double score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.create_time
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.id
     *
     * @return the value of question.id
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.id
     *
     * @param id the value for question.id
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.type
     *
     * @return the value of question.type
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.type
     *
     * @param type the value for question.type
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.score
     *
     * @return the value of question.score
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.score
     *
     * @param score the value for question.score
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.create_time
     *
     * @return the value of question.create_time
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.create_time
     *
     * @param createTime the value for question.create_time
     *
     * @mbggenerated Mon Jun 05 10:56:44 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}