package com.lanouit.exam.po;

import java.util.List;

import javax.validation.constraints.NotNull;

import com.lanouit.exam.validator.group.SubjectSaveGroup;
import com.lanouit.exam.validator.group.SubjectUpdateGroup;

public class Subject {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column subject.id
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column subject.subject_name
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	@NotNull(message = "科目名称不能空", groups = { SubjectSaveGroup.class,
			SubjectUpdateGroup.class })
	private String subjectName;

	private List<Position> positions;

	public List<Position> getPositions() {
		return positions;
	}

	public void setPositions(List<Position> positions) {
		this.positions = positions;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column subject.id
	 *
	 * @return the value of subject.id
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column subject.id
	 *
	 * @param id
	 *            the value for subject.id
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column subject.subject_name
	 *
	 * @return the value of subject.subject_name
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	public String getSubjectName() {
		return subjectName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column subject.subject_name
	 *
	 * @param subjectName
	 *            the value for subject.subject_name
	 *
	 * @mbggenerated Mon Jun 05 10:56:44 CST 2017
	 */
	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName == null ? null : subjectName.trim();
	}

	@Override
	public String toString() {
		return "Subject [id=" + id + ", subjectName=" + subjectName
				+ ", positions=" + positions + "]";
	}
	
	@Override
	public boolean equals(Object obj) {
		if(obj instanceof Subject) {
			return this.id == ((Subject)obj).getId();
		}
		return super.equals(obj);
	}

}